version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 6.0
  pre_build:
    commands:
      - dotnet restore ./demoapp.csproj
  build:
    commands:
      - dotnet build ./demoapp.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ ./demoapp.csproj
artifacts:
  files:
    - '**/*'