insert into council.Bin (council_name, landfill_yes, landfill_no, recycle_yes, recycle_no, green_yes, green_no, council_name_fk)
values  ('Ballarat City Council', 'Nappies, Wipes, Plastic Bags, Soft Plastics, Takeaway Coffee Cups, Straws, Toothpaste Tubes, Meat Trays, Toothbrushes, Gloves, Food Waste and etc.', ' E-waste, Medical Waste, Chemical Waste, Hazardous Materials and etc.', 'Glass Bottles and Jars, Milk and Juice Cartons, Aluminium/Tin/Steel Cans,  Plastics with Recycle Symbols 1, 2, 3, 4, 5, and 6, Paper Products and etc.            
', 'Medical Waste, Soft Plastics, Food Packaging, Clothing, Plastic Bags, Take Away Coffee Cups, Straws and Cutlery, E-Waste, Rubber, Plastics with Recycling Symbols 6 and 7 and etc.', 'Leaves, Weeds, Pruning, Grass, Flowers And Small Branches 10mm in Diameter And 55mm Long (Larger Logs Can Be Disposed At The Transfer Station) and etc.', 'Plastic Bag, Large Chunk Of Wood, Plant Pot, Food Waste, Animal Waste and etc.', null),
        ('Campaspe Shire Council', 'Nappies, Wipes, Plastic Bags, Soft Plastics, Takeaway Coffee Cups, Straws, Toothpaste Tubes, Meat Trays, Toothbrushes, Gloves and etc.', ' E-waste, Medical Waste, Chemical Waste, Hazardous Materials and etc.', 'Glass Bottles and Jars, Milk and Juice Cartons, Aluminium/Tin/Steel Cans,  Plastics with Recycle Symbols 1, 2, 3, 4, 5, and 6, Paper Products and etc.            
', 'Medical Waste, Soft Plastics, Food Packaging, Clothing, Plastic Bags, Take Away Coffee Cups, Straws and Cutlery, E-Waste, Rubber, Plastics with Recycling Symbols 6 and 7 and etc.', 'Food Waste, Tea Bags And Coffee Grounds, Used Paper Towel, Tissues And Napkins, Animal Poo, Lawn Clippings, Garden Prunings, Twigs And Branches (under 100mm in diameter), Compostable Bags and etc.              ', 'Plastic Bag, Large Chunk Of Wood, Plant Pot,  Animal Waste and etc.', null),
        ('Casey City Council', 'Nappies, Takeaway Coffee Cups, Straws and Cutlery(Biodegradable/Degradable ), Clothing(Old and Torn), Broken Glass and Ceramics, Black Plastics, Milk/juice Cartons or Tetra Pak,Plastic bags, Soft Plastics, Shredded Paper , Polystyrene, Plastics with Recycling Symbols 6 and 7 and etc.', ' E-waste, Medical Waste, Chemical Waste, Hazardous Materials and etc.', 'Glass Bottles and Jars, Milk and Juice Cartons, Aluminium/Tin/Steel Cans,  Plastics with Recycle Symbols 1, 2, 3, 4, 5, and 6, Paper Products and etc.            
', 'Medical Waste, Soft Plastics, Food Packaging, Clothing, Plastic Bags, Take Away Coffee Cups, Straws and Cutlery, E-Waste, Rubber, Plastics with Recycling Symbols 6 and 7 and etc.', 'Food Waste, Used Paper, Paper Towels, Napkins, Paper Bags, Newspaper And Tissues, Weeds And Flowers, Grass And Leaves, Garden Pruning (Including Weeds And Rose Trimmings), Small Sticks, Toothpicks, Skewers And Uncoated Chopsticks, Food-Spoiled Papers and etc.', 'Plastic Bag, Large Chunk Of Wood, Plant Pot, Food Waste, Animal Waste and etc.', null),
        ('Boroondara Council', 'Nappies, baby wipes, Plastic Bags, Soft Plastics, Cooked Bones, Oyster Shells, Tea Bags, Clothing(Old and Torn), Animal Waste, Broken Glasses and Cookware, Soiled Food Packaging and etc.', 'E-Waste, Medical Waste, Chemical Waste, Syringes And Needles, Hot Ashes, Building Or Excavation Materials, Including Timber, etc.', 'Glass Bottles and Jars, Milk and Juice Cartons, Aluminium/Tin/Steel Cans,  Plastics with Recycle Symbols 1, 2, 3, 4, 5, and 6, Paper Products and etc.            
', 'Medical Waste, E-Waste, Soft Plastics, Food Packaging, Clothing, Plastic Bags, Take Away Coffee Cups, Straws and Cutlery, Rubber, Plastics with Recycling Symbols 6 and 7 and etc.', 'Food Waste, Garden Waste, Most Dirty or Wet Cardboard and Paper, such as Newspaper and Tissues, and etc.', 'Tea Bags, Stickers On Fruits And Vegetables, Food Packaging, Plastic Waste, Animal Waste, and etc.
', null),
        ('Alpine Shire Council', 'Biodegradable/Degradable Plastics, Nappies, Waxed Cardboard , Broken Crockery or Glasses,
Foam, Styrofoam Trays (meat trays), Polystyrene, Broken toys, Wire, Rope, Clothing or Shoes, Feminine hygiene products, Takeaway Coffee Cups, Timber Offcuts, Vacuum Dust and etc.', 'E-Waste, Medical Waste, Chemical Waste, Syringes And Needles, Hot Ashes, Building Or Excavation Materials, Including Timber, etc.
', 'Glass Bottles and Jars, Aluminium and Steel Cans, Aluminium Foil (Srunched), Aerosol Cans, Foil Containers, Plastic Plant Pots, Milk and Juice Cartons and Bottles, Cardboard Boxes, Paper Products, Carboard, Hard Plastics, Etc.', 'Medical Waste, E-Waste, Soft Plastics, Food Packaging, Clothing, Plastic Bags, Take Away Coffee Cups, Straws and Cutlery, Rubber, Plastics with Recycling Symbols 6 and 7 and etc.', 'Food Waste, Garden Waste, Most Dirty or Wet Cardboard and Paper, such as Newspaper And Tissues, and etc.', 'Plastic Bag, Large Chunk Of Wood, Plant Pot, Food Waste, Animal Waste and etc.', null),
        ('Whittlesea Council', 'Wipes, Cigarette Butts, Coffee Pods, Disposable Masks And Gloves, Disposable Plates, Cups And Cutlery, Food And Garden Waste, Glassware And Ceramic Cookware, Drinking Glasses, Pyrex Glass,  Lids, Bottle Caps, Pump Sprays And Droppers, Milk And Juice Cartons, Medicines, Nappies, Sanitary And Incontinence Products, Polystyrene Food And Drink Containers, Trays And Packaging, Plant Pots, Plastic Straws And Takeaway Coffee Cups, Plastic Toys, Soft Plastics(Including Food/Cling Wrap, Plastic Bags And ', 'Building/Renovation Material, E-Waste, Gas Or Helium Bottles, Hot Ash, Household Chemicals Including Oil, Paint, Cleaning Products, Fertilisers And Car Care Products And Liquid Waste, Recyclable Items, Soil, Rocks Or Bricks, Syringes, etc.', 'Cans and Tins, Foil (Srunched into a Ball), Glass Bottles and Jars, Paper and Cardboard (excluding Paper/Hand Towels, Shopping Receipts, Serviettes and Tissues), Plastic Bottles and Containers Labelled with Code 1, 2, 3, 4 or 5 (no Plastic Bottle Lids), Etc.', 'Medical Waste, E-Waste, Soft Plastics, Food Packaging, Clothing, Plastic Bags, Take Away Coffee Cups, Straws And Cutlery, Rubber, Plastics With Recycling Symbols 6 And 7, Glassware And Ceramics, Bottle Caps, Pump Sprays And Droppers, Milk And Juice Cartons, X-Rays, Waxed Cardboard And Food Soiled Cardboard Or Paper and etc.', 'Leaves, Weeds, Pruning, Grass, Flowers And Small Branches 10mm in Diameter And 55mm Long (Larger Logs Can Be Disposed At The Transfer Station) and etc.', 'Plastic Bag, Large Chunk Of Wood, Plant Pot, Food Waste, Animal Waste and etc.', null),
        ('Great Dandenong Council', 'Nappies, Wipes, Plastic Bags, Soft Plastics, Takeaway Coffee Cups, Straws, Toothpaste Tubes, Meat Trays, Toothbrushes, Gloves and etc.', 'E-Waste, Medical Waste, Chemical Waste, Syringes And Needles, Hot Ashes, Building Or Excavation Materials, Including Timber, etc.
', 'Clean, Empty Cans and Aluminium/ Plastic Bottles and Containers from the Kitchen, Laundry and Bathroom(No Lids of any type),Paper Products, Milk and Juice Cartons, Cardboard, etc.', 'Medical Waste, E-Waste, Soft Plastics, Food Packaging, Clothing, Plastic Bags, Take Away Coffee Cups, Straws And Cutlery, Rubber, Plastics With Recycling Symbols 6 And 7, Glassware And Ceramics, Bottle Caps, Pump Sprays And Droppers, Milk And Juice Cartons, X-Rays, Waxed Cardboard And Food Soiled Cardboard Or Paper and etc.', 'Food Waste, Garden Waste and etc.', 'Plastic Bag, Large Chunk Of Wood, Plant Pot, Food Waste, Animal Waste and etc.', null);