insert into council.Policy (waste_type, council_name, waste_policy)
values  ('Aerosol Ccans (empty)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Aerosol Ccans (empty)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Aerosol Ccans (empty)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Aerosol Ccans (empty)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Aerosol Ccans (empty)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Aerosol Ccans (empty)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Aerosol Ccans (empty)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Alcohol bottles glass(no lids)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Alcohol bottles glass(no lids)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Alcohol bottles glass(no lids)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Alcohol bottles glass(no lids)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Alcohol bottles glass(no lids)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Alcohol bottles glass(no lids)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Alcohol bottles glass(no lids)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Aluminium cans', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Aluminium cans', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Aluminium cans', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Aluminium cans', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Aluminium cans', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Aluminium cans', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Aluminium cans', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Animal poo', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Animal poo', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Animal poo', 'Alpine Council', 'Put in your Garbage Bin or Compost Farm'),
        ('Animal poo', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Animal poo', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Animal poo', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Animal poo', 'Campaspe  Council', 'Put in your Green Bin'),
        ('Appliances (e-waste)', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Appliances (e-waste)', 'Casey City Council', 'Hard Waste Collection or Take to your nearst Recycing Centres. Fees may apply.'),
        ('Appliances (e-waste)', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Appliances (e-waste)', 'Dandenong Council', 'Hard Waste Collection or Recycing centres'),
        ('Appliances (e-waste)', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Appliances (e-waste)', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Appliances (e-waste)', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Baby wipes', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Baby wipes', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Baby wipes', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Baby wipes', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Baby wipes', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Baby wipes', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Baby wipes', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Baking paper', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Baking paper', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Baking paper', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Baking paper', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Baking paper', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Baking paper', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Baking paper', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Band aids', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Band aids', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Band aids', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Band aids', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Band aids', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Band aids', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Band aids', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Batteries (e-waste)', 'Ballarat City Council', 'Take to your nearst Woolworth, Aldi, Bunnings, Officework, BatteryWorld or Recycing Centres.'),
        ('Batteries (e-waste)', 'Casey City Council', 'Take to your nearst Woolworth, Aldi, Bunnings, Officework, BatteryWorld or Recycing Centres.'),
        ('Batteries (e-waste)', 'Alpine Council', 'Take to your nearst Woolworth, Aldi, Bunnings, Officework, BatteryWorld or Recycing Centres.'),
        ('Batteries (e-waste)', 'Dandenong Council', 'Take to your nearst Woolworth, Aldi, Bunnings, Officework, BatteryWorld or Recycing Centres.'),
        ('Batteries (e-waste)', 'Boroondara', 'Take to your nearst Woolworth, Aldi, Bunnings, Officework, BatteryWorld or Recycing Centres.'),
        ('Batteries (e-waste)', 'Whittlesea ', 'Take to your nearst Woolworth, Aldi, Bunnings, Officework, BatteryWorld or Recycing Centres.'),
        ('Batteries (e-waste)', 'Campaspe  Council', 'Take to your nearst Woolworth, Aldi, Bunnings, Officework, BatteryWorld or Recycing Centres.'),
        ('Bicycles', 'Ballarat City Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Bicycles', 'Casey City Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Bicycles', 'Alpine Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Bicycles', 'Dandenong Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Bicycles', 'Boroondara', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Bicycles', 'Whittlesea ', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Bicycles', 'Campaspe  Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Biscuit packaging', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Biscuit packaging', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Biscuit packaging', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Biscuit packaging', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Biscuit packaging', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Biscuit packaging', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Biscuit packaging', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Branches (trees)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Branches (trees)', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Branches (trees)', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Branches (trees)', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Branches (trees)', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Branches (trees)', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Branches (trees)', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Bread bag clips', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Bread bag clips', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Bread bag clips', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Bread bag clips', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Bread bag clips', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Bread bag clips', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Bread bag clips', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Bread bags (plastic)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Bread bags (plastic)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Bread bags (plastic)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Bread bags (plastic)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Bread bags (plastic)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Bread bags (plastic)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Bread bags (plastic)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Bubble wrap', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Bubble wrap', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Bubble wrap', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Bubble wrap', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Bubble wrap', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Bubble wrap', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Bubble wrap', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Cans (empty and clean aluminium, tin)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Cans (empty and clean aluminium, tin)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Cans (empty and clean aluminium, tin)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Cans (empty and clean aluminium, tin)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Cans (empty and clean aluminium, tin)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Cans (empty and clean aluminium, tin)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Cans (empty and clean aluminium, tin)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Car parts(metal or electronic)', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Car parts(metal or electronic)', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Car parts(metal or electronic)', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Car parts(metal or electronic)', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Car parts(metal or electronic)', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Car parts(metal or electronic)', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Car parts(metal or electronic)', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Cardboard', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Cardboard', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Cardboard', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Cardboard', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Cardboard', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Cardboard', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Cardboard', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Carpet', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Carpet', 'Casey City Council', 'Hard Waste Collection or Take to your nearst Recycing Centres. Fees may apply.'),
        ('Carpet', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Carpet', 'Dandenong Council', 'Hard Waste Collection or Recycing centres'),
        ('Carpet', 'Boroondara', 'Hard Waste Collection or Recycing centres'),
        ('Carpet', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Carpet', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Ceramics (broken)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Ceramics (broken)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Ceramics (broken)', 'Alpine Council', 'Put in your Garbage Bin or Recycing Centres'),
        ('Ceramics (broken)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Ceramics (broken)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Ceramics (broken)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Ceramics (broken)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Cereal box liners (plastic)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Cereal box liners (plastic)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Cereal box liners (plastic)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Cereal box liners (plastic)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Cereal box liners (plastic)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Cereal box liners (plastic)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Cereal box liners (plastic)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Chip packets (soft plastics)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Chip packets (soft plastics)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Chip packets (soft plastics)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Chip packets (soft plastics)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Chip packets (soft plastics)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Chip packets (soft plastics)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Chip packets (soft plastics)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Cigarette butts', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Cigarette butts', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Cigarette butts', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Cigarette butts', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Cigarette butts', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Cigarette butts', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Cigarette butts', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Cling wrap/plastic film', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Cling wrap/plastic film', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Cling wrap/plastic film', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Cling wrap/plastic film', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Cling wrap/plastic film', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Cling wrap/plastic film', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Cling wrap/plastic film', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Clothes( old and torn)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Clothes( old and torn)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Clothes( old and torn)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Clothes( old and torn)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Clothes( old and torn)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Clothes( old and torn)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Clothes( old and torn)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Clothes(good condition)', 'Ballarat City Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Clothes(good condition)', 'Casey City Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Clothes(good condition)', 'Alpine Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Clothes(good condition)', 'Dandenong Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Clothes(good condition)', 'Boroondara', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Clothes(good condition)', 'Whittlesea ', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Clothes(good condition)', 'Campaspe  Council', 'Take to your nearst Recycing Centres or donate to OP shop'),
        ('Coathangers', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Coathangers', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Coathangers', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Coathangers', 'Dandenong Council', 'Put in your Garbage Bin or Recycling centres'),
        ('Coathangers', 'Boroondara', 'Put in your Garbage Bin or Recycling centres'),
        ('Coathangers', 'Whittlesea ', 'Put in your Garbage Bin or Recycling centres'),
        ('Coathangers', 'Campaspe  Council', 'Put in your Garbage Bin or Recycling centres'),
        ('Coffee cups', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Coffee cups', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Coffee cups', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Coffee cups', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Coffee cups', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Coffee cups', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Coffee cups', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Coffee grounds', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Coffee grounds', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Coffee grounds', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Coffee grounds', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Coffee grounds', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Coffee grounds', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Coffee grounds', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Dog and cat food pouches', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Dog and cat food pouches', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Dog and cat food pouches', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Dog and cat food pouches', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Dog and cat food pouches', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Dog and cat food pouches', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Dog and cat food pouches', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Dog, cat food tins (clean) ', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Dog, cat food tins (clean) ', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Dog, cat food tins (clean) ', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Dog, cat food tins (clean) ', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Dog, cat food tins (clean) ', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Dog, cat food tins (clean) ', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Dog, cat food tins (clean) ', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Egg cartons', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Egg cartons', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Egg cartons', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Egg cartons', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Egg cartons', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Egg cartons', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Egg cartons', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Envelopes (paper & cardboard)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Envelopes (paper & cardboard)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Envelopes (paper & cardboard)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Envelopes (paper & cardboard)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Envelopes (paper & cardboard)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Envelopes (paper & cardboard)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Envelopes (paper & cardboard)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Face wipes', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Face wipes', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Face wipes', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Face wipes', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Face wipes', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Face wipes', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Face wipes', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Flowers', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Flowers', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Flowers', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Flowers', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Flowers', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Flowers', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Flowers', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Foam boxes', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Foam boxes', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Foam boxes', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Foam boxes', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Foam boxes', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Foam boxes', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Foam boxes', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Food waste', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Food waste', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Food waste', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Food waste', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Food waste', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Food waste', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Food waste', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Fresh produce bags(soft plastic)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Fresh produce bags(soft plastic)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Fresh produce bags(soft plastic)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Fresh produce bags(soft plastic)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Fresh produce bags(soft plastic)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Fresh produce bags(soft plastic)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Fresh produce bags(soft plastic)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Frozen food or veggie bags', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Frozen food or veggie bags', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Frozen food or veggie bags', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Frozen food or veggie bags', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Frozen food or veggie bags', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Frozen food or veggie bags', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Frozen food or veggie bags', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Furniture (good condition)', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Furniture (good condition)', 'Casey City Council', 'Hard Waste Collection or Take to your nearst Recycing Centres. Fees may apply.'),
        ('Furniture (good condition)', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Furniture (good condition)', 'Dandenong Council', 'Hard Waste Collection or Recycing centres'),
        ('Furniture (good condition)', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Furniture (good condition)', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Furniture (good condition)', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Gas bottles (all types)', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Gas bottles (all types)', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Gas bottles (all types)', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Gas bottles (all types)', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Gas bottles (all types)', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Gas bottles (all types)', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Gas bottles (all types)', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Glass bottles and jars', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Glass bottles and jars', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Glass bottles and jars', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Glass bottles and jars', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Glass bottles and jars', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Glass bottles and jars', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Glass bottles and jars', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Grass clippings', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Grass clippings', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Grass clippings', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Grass clippings', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Grass clippings', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Grass clippings', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Grass clippings', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Greeting cards', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Greeting cards', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Greeting cards', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Greeting cards', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Greeting cards', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Greeting cards', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Greeting cards', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Hair (human, animal) ', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Hair (human, animal) ', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Hair (human, animal) ', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Hair (human, animal) ', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Hair (human, animal) ', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Hair (human, animal) ', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Hair (human, animal) ', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Ice cream containers(clean)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Ice cream containers(clean)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Ice cream containers(clean)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Ice cream containers(clean)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Ice cream containers(clean)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Ice cream containers(clean)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Ice cream containers(clean)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Ice cream wrappers', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Ice cream wrappers', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Ice cream wrappers', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Ice cream wrappers', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Ice cream wrappers', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Ice cream wrappers', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Ice cream wrappers', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Jars (glass) no lids', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Jars (glass) no lids', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Jars (glass) no lids', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Jars (glass) no lids', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Jars (glass) no lids', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Jars (glass) no lids', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Jars (glass) no lids', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Juice bottles (with no handle)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Juice bottles (with no handle)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Juice bottles (with no handle)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Juice bottles (with no handle)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Juice bottles (with no handle)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Juice bottles (with no handle)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Juice bottles (with no handle)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Kitty litter', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Kitty litter', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Kitty litter', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Kitty litter', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Kitty litter', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Kitty litter', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Kitty litter', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Laminated paper', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Laminated paper', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Laminated paper', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Laminated paper', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Laminated paper', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Laminated paper', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Laminated paper', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Lawn mowers', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Lawn mowers', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Lawn mowers', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Lawn mowers', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Lawn mowers', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Lawn mowers', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Lawn mowers', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Leaves ', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Leaves ', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Leaves ', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Leaves ', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Leaves ', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Leaves ', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Leaves ', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Light bulbs', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Light bulbs', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Light bulbs', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Light bulbs', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Light bulbs', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Light bulbs', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Light bulbs', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Lolly bags/wrappers', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Lolly bags/wrappers', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Lolly bags/wrappers', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Lolly bags/wrappers', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Lolly bags/wrappers', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Lolly bags/wrappers', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Lolly bags/wrappers', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Long life cartons', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Long life cartons', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Long life cartons', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Long life cartons', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Long life cartons', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Long life cartons', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Long life cartons', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Magazine wrappers (soft plastic)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Magazine wrappers (soft plastic)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Magazine wrappers (soft plastic)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Magazine wrappers (soft plastic)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Magazine wrappers (soft plastic)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Magazine wrappers (soft plastic)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Magazine wrappers (soft plastic)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Magazines', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Magazines', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Magazines', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Magazines', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Magazines', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Magazines', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Magazines', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Margarine containers (clean)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Margarine containers (clean)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Margarine containers (clean)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Margarine containers (clean)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Margarine containers (clean)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Margarine containers (clean)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Margarine containers (clean)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Mask Disposable', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Mask Disposable', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Mask Disposable', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Mask Disposable', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Mask Disposable', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Mask Disposable', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Mask Disposable', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Mattresses', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Mattresses', 'Casey City Council', 'Hard Waste Collection or Take to your nearst Recycing Centres. Fees may apply.'),
        ('Mattresses', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Mattresses', 'Dandenong Council', 'Hard Waste Collection or Recycing centres'),
        ('Mattresses', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Mattresses', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Mattresses', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Meat and fish bones', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Meat and fish bones', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Meat and fish bones', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Meat and fish bones', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Meat and fish bones', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Meat and fish bones', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Meat and fish bones', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Meat trays (polystyrene plastic #6)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Meat trays (polystyrene plastic #6)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Meat trays (polystyrene plastic #6)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Meat trays (polystyrene plastic #6)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Meat trays (polystyrene plastic #6)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Meat trays (polystyrene plastic #6)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Meat trays (polystyrene plastic #6)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Medicine bottles (glass)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Medicine bottles (glass)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Medicine bottles (glass)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Medicine bottles (glass)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Medicine bottles (glass)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Medicine bottles (glass)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Medicine bottles (glass)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Nail Polish', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Nail Polish', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Nail Polish', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Nail Polish', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Nail Polish', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Nail Polish', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Nail Polish', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Napkins', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Napkins', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Napkins', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Napkins', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Napkins', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Napkins', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Napkins', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Nappies', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Nappies', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Nappies', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Nappies', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Nappies', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Nappies', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Nappies', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Needles(sewing)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Needles(sewing)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Needles(sewing)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Needles(sewing)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Needles(sewing)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Needles(sewing)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Needles(sewing)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Newspaper', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Newspaper', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Newspaper', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Newspaper', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Newspaper', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Newspaper', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Newspaper', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Office paper', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Office paper', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Office paper', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Office paper', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Office paper', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Office paper', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Office paper', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Oil (cooking)', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Oil (cooking)', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Oil (cooking)', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Oil (cooking)', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Oil (cooking)', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Oil (cooking)', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Oil (cooking)', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Oil (engine)', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Oil (engine)', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Oil (engine)', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Oil (engine)', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Oil (engine)', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Oil (engine)', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Oil (engine)', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint ', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint ', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint ', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint ', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint ', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint ', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint ', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint tins', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint tins', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint tins', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint tins', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint tins', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint tins', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paint tins', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Paper cups', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Paper cups', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Paper cups', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Paper cups', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Paper cups', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Paper cups', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Paper cups', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Paper towel packaging (soft plastic)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Paper towel packaging (soft plastic)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Paper towel packaging (soft plastic)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Paper towel packaging (soft plastic)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Paper towel packaging (soft plastic)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Paper towel packaging (soft plastic)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Paper towel packaging (soft plastic)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Paper towel/tissues', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Paper towel/tissues', 'Casey City Council', 'Put in your Food & Garden Bin.'),
        ('Paper towel/tissues', 'Alpine Council', 'Put in your Food & Garden Bin.'),
        ('Paper towel/tissues', 'Dandenong Council', 'Put in your Food & Garden Bin.'),
        ('Paper towel/tissues', 'Boroondara', 'Put in your Food & Garden Bin.'),
        ('Paper towel/tissues', 'Whittlesea ', 'Put in your Food & Garden Bin.'),
        ('Paper towel/tissues', 'Campaspe  Council', 'Put in your Food & Garden Bin.'),
        ('Pasta bags', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Pasta bags', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Pasta bags', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Pasta bags', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Pasta bags', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Pasta bags', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Pasta bags', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Pizza boxes (clean)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Pizza boxes (clean)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Pizza boxes (clean)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Pizza boxes (clean)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Pizza boxes (clean)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Pizza boxes (clean)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Pizza boxes (clean)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Pizza boxes (oily)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Pizza boxes (oily)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Pizza boxes (oily)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Pizza boxes (oily)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Pizza boxes (oily)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Pizza boxes (oily)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Pizza boxes (oily)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Plant pots (empty)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Plant pots (empty)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Plant pots (empty)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Plant pots (empty)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Plant pots (empty)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Plant pots (empty)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Plant pots (empty)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Plaster board', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Plaster board', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Plaster board', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Plaster board', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Plaster board', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Plaster board', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Plaster board', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Plastic containers (rigid plastic)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Plastic containers (rigid plastic)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Plastic containers (rigid plastic)', 'Alpine Council', 'Put in yoru Recycle Bin.'),
        ('Plastic containers (rigid plastic)', 'Dandenong Council', 'Put in yoru Recycle Bin.'),
        ('Plastic containers (rigid plastic)', 'Boroondara', 'Put in yoru Recycle Bin.'),
        ('Plastic containers (rigid plastic)', 'Whittlesea ', 'Put in yoru Recycle Bin.'),
        ('Plastic containers (rigid plastic)', 'Campaspe  Council', 'Put in yoru Recycle Bin.'),
        ('Plastic shopping bags', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Plastic shopping bags', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Plastic shopping bags', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Plastic shopping bags', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Plastic shopping bags', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Plastic shopping bags', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Plastic shopping bags', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Rubber products', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Rubber products', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Rubber products', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Rubber products', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Rubber products', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Rubber products', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Rubber products', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Sanitary items (including compostable)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Sanitary items (including compostable)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Sanitary items (including compostable)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Sanitary items (including compostable)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Sanitary items (including compostable)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Sanitary items (including compostable)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Sanitary items (including compostable)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Sauce bottles(empty)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Sauce bottles(empty)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Sauce bottles(empty)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Sauce bottles(empty)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Sauce bottles(empty)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Sauce bottles(empty)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Sauce bottles(empty)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Shampoo and conditioner bottles', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Shampoo and conditioner bottles', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Shampoo and conditioner bottles', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Shampoo and conditioner bottles', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Shampoo and conditioner bottles', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Shampoo and conditioner bottles', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Shampoo and conditioner bottles', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Shoes(old and torn)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Shoes(old and torn)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Shoes(old and torn)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Shoes(old and torn)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Shoes(old and torn)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Shoes(old and torn)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Shoes(old and torn)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Straw(plastic, paper or compostable)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Straw(plastic, paper or compostable)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Straw(plastic, paper or compostable)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Straw(plastic, paper or compostable)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Straw(plastic, paper or compostable)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Straw(plastic, paper or compostable)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Straw(plastic, paper or compostable)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Takeaway container(plastic)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Takeaway container(plastic)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Takeaway container(plastic)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Takeaway container(plastic)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Takeaway container(plastic)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Takeaway container(plastic)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Takeaway container(plastic)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Tea bags', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Tea bags', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Tea bags', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Tea bags', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Tea bags', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Tea bags', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Tea bags', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Telephone books', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Telephone books', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Telephone books', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Telephone books', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Telephone books', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Telephone books', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Telephone books', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Tissue box with plastic removed', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Tissue box with plastic removed', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Tissue box with plastic removed', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Tissue box with plastic removed', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Tissue box with plastic removed', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Tissue box with plastic removed', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Tissue box with plastic removed', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Toothpaste tubes & brushes', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Toothpaste tubes & brushes', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Toothpaste tubes & brushes', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Toothpaste tubes & brushes', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Toothpaste tubes & brushes', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Toothpaste tubes & brushes', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Toothpaste tubes & brushes', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Toys(plush, plastic)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Toys(plush, plastic)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Toys(plush, plastic)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Toys(plush, plastic)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Toys(plush, plastic)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Toys(plush, plastic)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Toys(plush, plastic)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Tyres', 'Ballarat City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Tyres', 'Casey City Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Tyres', 'Alpine Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Tyres', 'Dandenong Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Tyres', 'Boroondara', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Tyres', 'Whittlesea ', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Tyres', 'Campaspe  Council', 'Take to your nearst Recycing Centres. Fees may apply.'),
        ('Window glass(broken-wrapped)', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Window glass(broken-wrapped)', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Window glass(broken-wrapped)', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Window glass(broken-wrapped)', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Window glass(broken-wrapped)', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Window glass(broken-wrapped)', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Window glass(broken-wrapped)', 'Campaspe  Council', 'Put in your Garbage Bin.'),
        ('Yoghurt containers (clean)', 'Ballarat City Council', 'Put in your Recycle Bin.'),
        ('Yoghurt containers (clean)', 'Casey City Council', 'Put in your Recycle Bin.'),
        ('Yoghurt containers (clean)', 'Alpine Council', 'Put in your Recycle Bin.'),
        ('Yoghurt containers (clean)', 'Dandenong Council', 'Put in your Recycle Bin.'),
        ('Yoghurt containers (clean)', 'Boroondara', 'Put in your Recycle Bin.'),
        ('Yoghurt containers (clean)', 'Whittlesea ', 'Put in your Recycle Bin.'),
        ('Yoghurt containers (clean)', 'Campaspe  Council', 'Put in your Recycle Bin.'),
        ('Yoghurt/baby food squeeze pouches with lid', 'Ballarat City Council', 'Put in your Garbage Bin.'),
        ('Yoghurt/baby food squeeze pouches with lid', 'Casey City Council', 'Put in your Garbage Bin.'),
        ('Yoghurt/baby food squeeze pouches with lid', 'Alpine Council', 'Put in your Garbage Bin.'),
        ('Yoghurt/baby food squeeze pouches with lid', 'Dandenong Council', 'Put in your Garbage Bin.'),
        ('Yoghurt/baby food squeeze pouches with lid', 'Boroondara', 'Put in your Garbage Bin.'),
        ('Yoghurt/baby food squeeze pouches with lid', 'Whittlesea ', 'Put in your Garbage Bin.'),
        ('Yoghurt/baby food squeeze pouches with lid', 'Campaspe  Council', 'Put in your Garbage Bin.');