insert into council.Postcode (locality_name, postcode, council_name)
values  ('Abbeyard', 3737, 'Alpine Shire Council'),
        ('Bogong', 3699, 'Alpine Shire Council'),
        ('Bright', 3741, 'Alpine Shire Council'),
        ('Buckland', 3740, 'Alpine Shire Council'),
        ('Coral Bank', 3691, 'Alpine Shire Council'),
        ('Dinner Plain', 3898, 'Alpine Shire Council'),
        ('Eurobin', 3739, 'Alpine Shire Council'),
        ('Ovens', 3738, 'Alpine Shire Council'),
        ('Tawonga', 3697, 'Alpine Shire Council'),
        ('Tawonga South', 3698, 'Alpine Shire Council'),
        ('Wandiligong', 3744, 'Alpine Shire Council'),
        ('Ararat', 3377, 'Ararat Rural City Council'),
        ('Ballyrogan', 3375, 'Ararat Rural City Council'),
        ('Black Range', 3381, 'Ararat Rural City Council'),
        ('Bornes Hill', 3379, 'Ararat Rural City Council'),
        ('Carranballac', 3361, 'Ararat Rural City Council'),
        ('Elmhurst', 3469, 'Ararat Rural City Council'),
        ('Glenthompson', 3293, 'Ararat Rural City Council'),
        ('Great Western', 3374, 'Ararat Rural City Council'),
        ('Lake Bolac', 3351, 'Ararat Rural City Council'),
        ('Pura Pura', 3271, 'Ararat Rural City Council'),
        ('Stoneleigh', 3373, 'Ararat Rural City Council'),
        ('Tatyoon', 3378, 'Ararat Rural City Council'),
        ('Woorndoo', 3272, 'Ararat Rural City Council'),
        ('Addington', 3352, 'Ballarat City Council'),
        ('Alfredton', 3350, 'Ballarat City Council'),
        ('Ascot', 3364, 'Ballarat City Council'),
        ('Buninyong', 3357, 'Ballarat City Council'),
        ('Creswick', 3363, 'Ballarat City Council'),
        ('Delacombe', 3356, 'Ballarat City Council'),
        ('Lake Gardens', 3355, 'Ballarat City Council'),
        ('Winter Valley', 3358, 'Ballarat City Council'),
        ('Bellfield', 3081, 'Banyule City Council'),
        ('Briar Hill', 3088, 'Banyule City Council'),
        ('Bundoora', 3083, 'Banyule City Council'),
        ('Eaglemont', 3084, 'Banyule City Council'),
        ('Eltham', 3095, 'Banyule City Council'),
        ('Ivanhoe', 3079, 'Banyule City Council'),
        ('Lower Plenty', 3093, 'Banyule City Council'),
        ('Macleod', 3085, 'Banyule City Council'),
        ('Montmorency', 3094, 'Banyule City Council'),
        ('Watsonia', 3087, 'Banyule City Council'),
        ('Adams Estate', 3984, 'Bass Coast Shire Council'),
        ('Almurta', 3979, 'Bass Coast Shire Council'),
        ('Anderson', 3995, 'Bass Coast Shire Council'),
        ('Bass', 3991, 'Bass Coast Shire Council'),
        ('Cape Woolamai', 3925, 'Bass Coast Shire Council'),
        ('Cowes', 3922, 'Bass Coast Shire Council'),
        ('Dalyston', 3992, 'Bass Coast Shire Council'),
        ('Glen Forbes', 3990, 'Bass Coast Shire Council'),
        ('Inverloch', 3996, 'Bass Coast Shire Council'),
        ('Kongwak', 3951, 'Bass Coast Shire Council'),
        ('Krowera', 3945, 'Bass Coast Shire Council'),
        ('Rhyll', 3923, 'Bass Coast Shire Council'),
        ('Aberfeldy', 3825, 'Baw Baw Shire Council'),
        ('Allambee', 3823, 'Baw Baw Shire Council'),
        ('Allambee Reserve', 3871, 'Baw Baw Shire Council'),
        ('Athlone', 3818, 'Baw Baw Shire Council'),
        ('Bona Vista', 3820, 'Baw Baw Shire Council'),
        ('Brandy Creek', 3821, 'Baw Baw Shire Council'),
        ('Childers', 3824, 'Baw Baw Shire Council'),
        ('Cloverlea', 3822, 'Baw Baw Shire Council'),
        ('Heath Hill', 3981, 'Baw Baw Shire Council'),
        ('Icy Creek', 3833, 'Baw Baw Shire Council'),
        ('Labertouche', 3816, 'Baw Baw Shire Council'),
        ('Mountain View', 3988, 'Baw Baw Shire Council'),
        ('Nayook', 3832, 'Baw Baw Shire Council'),
        ('Neerim', 3831, 'Baw Baw Shire Council'),
        ('Nyora', 3987, 'Baw Baw Shire Council'),
        ('Strzelecki', 3950, 'Baw Baw Shire Council'),
        ('Thorpdale', 3835, 'Baw Baw Shire Council'),
        ('Trida', 3953, 'Baw Baw Shire Council'),
        ('Beaumaris', 3193, 'Bayside City Council'),
        ('Brighton', 3186, 'Bayside City Council'),
        ('Brighton East', 3187, 'Bayside City Council'),
        ('Cheltenham', 3192, 'Bayside City Council'),
        ('Hampton', 3188, 'Bayside City Council'),
        ('Hampton', 3191, 'Bayside City Council'),
        ('Highett', 3190, 'Bayside City Council'),
        ('Archerton', 3723, 'Benalla Rural City Council'),
        ('Baddaginnie', 3670, 'Benalla Rural City Council'),
        ('Benalla', 3672, 'Benalla Rural City Council'),
        ('Boweya', 3675, 'Benalla Rural City Council'),
        ('Boxwood', 3725, 'Benalla Rural City Council'),
        ('Broken Creek', 3673, 'Benalla Rural City Council'),
        ('Bungeet', 3726, 'Benalla Rural City Council'),
        ('Ashburton', 3147, 'Boroondara City Council'),
        ('Balwyn', 3103, 'Boroondara City Council'),
        ('Balwyn North', 3104, 'Boroondara City Council'),
        ('Camberwell', 3124, 'Boroondara City Council'),
        ('Canterbury', 3126, 'Boroondara City Council'),
        ('Glen Iris', 3146, 'Boroondara City Council'),
        ('Hawthorn', 3122, 'Boroondara City Council'),
        ('Hawthorn East', 3123, 'Boroondara City Council'),
        ('Kew', 3101, 'Boroondara City Council'),
        ('Kew East', 3102, 'Boroondara City Council'),
        ('Mont Albert', 3127, 'Boroondara City Council'),
        ('Albanvale', 3021, 'Brimbank City Council'),
        ('Albion', 3020, 'Brimbank City Council'),
        ('Ardeer', 3022, 'Brimbank City Council'),
        ('Brooklyn', 3012, 'Brimbank City Council'),
        ('Cairnlea', 3023, 'Brimbank City Council'),
        ('Delahey', 3037, 'Brimbank City Council'),
        ('Derrimut', 3026, 'Brimbank City Council'),
        ('Keilor', 3036, 'Brimbank City Council'),
        ('Keilor Downs', 3038, 'Brimbank City Council'),
        ('Keilor East', 3033, 'Brimbank City Council'),
        ('Keilor Park', 3042, 'Brimbank City Council'),
        ('Tullamarine', 3043, 'Brimbank City Council'),
        ('Ballapur', 3483, 'Buloke Shire Council'),
        ('Banyan', 3485, 'Buloke Shire Council'),
        ('Barrakee', 3525, 'Buloke Shire Council'),
        ('Berriwillock', 3531, 'Buloke Shire Council'),
        ('Bimbourie', 3533, 'Buloke Shire Council'),
        ('Bunguluke', 3527, 'Buloke Shire Council'),
        ('Carron', 3480, 'Buloke Shire Council'),
        ('Cokum', 3542, 'Buloke Shire Council'),
        ('Coonooer Bridge', 3477, 'Buloke Shire Council'),
        ('Culgoa', 3530, 'Buloke Shire Council'),
        ('Dooboobetic', 3478, 'Buloke Shire Council'),
        ('Kalpienung', 3529, 'Buloke Shire Council'),
        ('Massey', 3482, 'Buloke Shire Council'),
        ('Reedy Dam', 3395, 'Buloke Shire Council'),
        ('Richmond Plains', 3518, 'Buloke Shire Council'),
        ('Springfield', 3544, 'Buloke Shire Council'),
        ('Turriff East', 3488, 'Buloke Shire Council'),
        ('Wilkur', 3393, 'Buloke Shire Council'),
        ('Ballendella', 3561, 'Campaspe Shire Council'),
        ('Bamawm Extension', 3564, 'Campaspe Shire Council'),
        ('Burnewang', 3558, 'Campaspe Shire Council'),
        ('Burramboot', 3559, 'Campaspe Shire Council'),
        ('Carag Carag', 3623, 'Campaspe Shire Council'),
        ('Cornella', 3551, 'Campaspe Shire Council'),
        ('Girgarre', 3624, 'Campaspe Shire Council'),
        ('Gunbower', 3566, 'Campaspe Shire Council'),
        ('Kotta', 3565, 'Campaspe Shire Council'),
        ('Koyuga', 3622, 'Campaspe Shire Council'),
        ('Kyabram', 3620, 'Campaspe Shire Council'),
        ('Kyvalley', 3621, 'Campaspe Shire Council'),
        ('Lockington', 3563, 'Campaspe Shire Council'),
        ('Milloo', 3572, 'Campaspe Shire Council'),
        ('Mitiamo', 3573, 'Campaspe Shire Council'),
        ('Moora', 3612, 'Campaspe Shire Council'),
        ('Muskerry', 3557, 'Campaspe Shire Council'),
        ('Redcastle', 3523, 'Campaspe Shire Council'),
        ('Torrumbarry', 3562, 'Campaspe Shire Council'),
        ('Avonsleigh', 3782, 'Cardinia Shire Council'),
        ('Beaconsfield', 3807, 'Cardinia Shire Council'),
        ('Beaconsfield Upper', 3808, 'Cardinia Shire Council'),
        ('Bunyip', 3815, 'Cardinia Shire Council'),
        ('Cardinia', 3978, 'Cardinia Shire Council'),
        ('Cockatoo', 3781, 'Cardinia Shire Council'),
        ('Cora Lynn', 3814, 'Cardinia Shire Council'),
        ('Gembrook', 3783, 'Cardinia Shire Council'),
        ('Maryknoll', 3812, 'Cardinia Shire Council'),
        ('Menzies Creek', 3159, 'Cardinia Shire Council'),
        ('Officer', 3809, 'Cardinia Shire Council'),
        ('Pakenham', 3810, 'Cardinia Shire Council'),
        ('Tooradin', 3980, 'Cardinia Shire Council'),
        ('Tynong', 3813, 'Cardinia Shire Council'),
        ('Berwick', 3806, 'Casey City Council'),
        ('Botanic Ridge', 3977, 'Casey City Council'),
        ('Doveton', 3177, 'Casey City Council'),
        ('Endeavour Hills', 3802, 'Casey City Council'),
        ('Hallam', 3803, 'Casey City Council'),
        ('Hampton Park', 3976, 'Casey City Council'),
        ('Lynbrook', 3975, 'Casey City Council'),
        ('Lysterfield South', 3156, 'Casey City Council'),
        ('Narre Warren', 3805, 'Casey City Council'),
        ('Narre Warren North', 3804, 'Casey City Council'),
        ('Pearcedale', 3912, 'Casey City Council'),
        ('Adelaide Lead', 3465, 'Central Goldfields Shire Council'),
        ('Amherst', 3371, 'Central Goldfields Shire Council'),
        ('Archdale', 3475, 'Central Goldfields Shire Council'),
        ('Bet Bet', 3472, 'Central Goldfields Shire Council'),
        ('Carisbrook', 3464, 'Central Goldfields Shire Council'),
        ('Glengower', 3370, 'Central Goldfields Shire Council'),
        ('Alvie', 3249, 'Colac Otway Shire Council'),
        ('Apollo Bay', 3233, 'Colac Otway Shire Council'),
        ('Barunah Plains', 3329, 'Colac Otway Shire Council'),
        ('Barwon Downs', 3243, 'Colac Otway Shire Council'),
        ('Beeac', 3251, 'Colac Otway Shire Council'),
        ('Beech Forest', 3237, 'Colac Otway Shire Council'),
        ('Birregurra', 3242, 'Colac Otway Shire Council'),
        ('Bungador', 3260, 'Colac Otway Shire Council'),
        ('Carlisle River', 3239, 'Colac Otway Shire Council'),
        ('Colac', 3250, 'Colac Otway Shire Council'),
        ('Cororooke', 3254, 'Colac Otway Shire Council'),
        ('Cressy', 3322, 'Colac Otway Shire Council'),
        ('Forrest', 3236, 'Colac Otway Shire Council'),
        ('Glenaire', 3238, 'Colac Otway Shire Council'),
        ('Grey River', 3234, 'Colac Otway Shire Council'),
        ('Jancourt East', 3266, 'Colac Otway Shire Council'),
        ('Ombersley', 3241, 'Colac Otway Shire Council'),
        ('Pennyroyal', 3235, 'Colac Otway Shire Council'),
        ('Wingeel', 3321, 'Colac Otway Shire Council'),
        ('Ayrford', 3268, 'Corangamite Shire Council'),
        ('Berrybank', 3323, 'Corangamite Shire Council'),
        ('Boorcan', 3265, 'Corangamite Shire Council'),
        ('Derrinallum', 3325, 'Corangamite Shire Council'),
        ('Lismore', 3324, 'Corangamite Shire Council'),
        ('Peterborough', 3270, 'Corangamite Shire Council'),
        ('Port Campbell', 3269, 'Corangamite Shire Council'),
        ('Scotts Creek', 3267, 'Corangamite Shire Council'),
        ('Terang', 3264, 'Corangamite Shire Council'),
        ('Alphington', 3078, 'Darebin City Council'),
        ('Coburg', 3058, 'Darebin City Council'),
        ('Northcote', 3070, 'Darebin City Council'),
        ('Preston', 3072, 'Darebin City Council'),
        ('Reservoir', 3073, 'Darebin City Council'),
        ('Thornbury', 3071, 'Darebin City Council'),
        ('Bairnsdale', 3875, 'East Gippsland Shire Council'),
        ('Bellbird Creek', 3889, 'East Gippsland Shire Council'),
        ('Benambra', 3900, 'East Gippsland Shire Council'),
        ('Bendoc', 3888, 'East Gippsland Shire Council'),
        ('Bindi', 3896, 'East Gippsland Shire Council'),
        ('Boole Poole', 3880, 'East Gippsland Shire Council'),
        ('Bruthen', 3885, 'East Gippsland Shire Council'),
        ('Buldah', 3890, 'East Gippsland Shire Council'),
        ('Bumberrah', 3902, 'East Gippsland Shire Council'),
        ('Cobbannah', 3862, 'East Gippsland Shire Council'),
        ('Dartmouth', 3701, 'East Gippsland Shire Council'),
        ('Doctors Flat', 3895, 'East Gippsland Shire Council'),
        ('Eagle Point', 3878, 'East Gippsland Shire Council'),
        ('Fernbank', 3864, 'East Gippsland Shire Council'),
        ('Genoa', 3891, 'East Gippsland Shire Council'),
        ('Kalimna', 3909, 'East Gippsland Shire Council'),
        ('Lake Tyers', 3887, 'East Gippsland Shire Council'),
        ('Lindenow', 3865, 'East Gippsland Shire Council'),
        ('Mallacoota', 3892, 'East Gippsland Shire Council'),
        ('Metung', 3904, 'East Gippsland Shire Council'),
        ('Nariel Valley', 3707, 'East Gippsland Shire Council'),
        ('Newmerella', 3886, 'East Gippsland Shire Council'),
        ('Nicholson', 3882, 'East Gippsland Shire Council'),
        ('Swan Reach', 3903, 'East Gippsland Shire Council'),
        ('Tambo Crossing', 3893, 'East Gippsland Shire Council'),
        ('Carrum Downs', 3201, 'Frankston City Council'),
        ('Frankston', 3199, 'Frankston City Council'),
        ('Frankston North', 3200, 'Frankston City Council'),
        ('Langwarrin', 3910, 'Frankston City Council'),
        ('Langwarrin South', 3911, 'Frankston City Council'),
        ('Seaford', 3198, 'Frankston City Council'),
        ('Appin', 3579, 'Gannawarra Shire Council'),
        ('Burkes Bridge', 3568, 'Gannawarra Shire Council'),
        ('Cannie', 3540, 'Gannawarra Shire Council'),
        ('Gredgwin', 3537, 'Gannawarra Shire Council'),
        ('Horfield', 3567, 'Gannawarra Shire Council'),
        ('Koondrook', 3580, 'Gannawarra Shire Council'),
        ('Lake Charm', 3581, 'Gannawarra Shire Council'),
        ('Meatian', 3585, 'Gannawarra Shire Council'),
        ('Bentleigh', 3204, 'Glen Eira City Council'),
        ('Bentleigh East', 3165, 'Glen Eira City Council'),
        ('Carnegie', 3163, 'Glen Eira City Council'),
        ('Caulfield', 3162, 'Glen Eira City Council'),
        ('Caulfield East', 3145, 'Glen Eira City Council'),
        ('Caulfield North', 3161, 'Glen Eira City Council'),
        ('Elsternwick', 3185, 'Glen Eira City Council'),
        ('St Kilda East', 3183, 'Glen Eira City Council'),
        ('Allestree', 3305, 'Glenelg Shire Council'),
        ('Bahgallah', 3312, 'Glenelg Shire Council'),
        ('Branxholme', 3302, 'Glenelg Shire Council'),
        ('Breakaway Creek', 3303, 'Glenelg Shire Council'),
        ('Casterton', 3311, 'Glenelg Shire Council'),
        ('Dartmoor', 3304, 'Glenelg Shire Council'),
        ('Digby', 3309, 'Glenelg Shire Council'),
        ('Merino', 3310, 'Glenelg Shire Council'),
        ('Muntham', 3315, 'Glenelg Shire Council'),
        ('Narrawong', 3285, 'Glenelg Shire Council'),
        ('Nelson', 3292, 'Glenelg Shire Council'),
        ('Tahara', 3301, 'Glenelg Shire Council'),
        ('Anakie', 3213, 'Golden Plains Shire Council'),
        ('Bamganie', 3333, 'Golden Plains Shire Council'),
        ('Bannockburn', 3331, 'Golden Plains Shire Council'),
        ('Durdidwarrah', 3342, 'Golden Plains Shire Council'),
        ('Happy Valley', 3360, 'Golden Plains Shire Council'),
        ('Lethbridge', 3332, 'Golden Plains Shire Council'),
        ('Murgheboluc', 3218, 'Golden Plains Shire Council'),
        ('Rokewood', 3330, 'Golden Plains Shire Council'),
        ('Teesdale', 3328, 'Golden Plains Shire Council'),
        ('Bendigo', 3550, 'Greater Bendigo City Council'),
        ('Big Hill', 3555, 'Greater Bendigo City Council'),
        ('California Gully', 3556, 'Greater Bendigo City Council'),
        ('Drummartin', 3570, 'Greater Bendigo City Council'),
        ('Harcourt North', 3453, 'Greater Bendigo City Council'),
        ('Leichardt', 3516, 'Greater Bendigo City Council'),
        ('Lyal', 3444, 'Greater Bendigo City Council'),
        ('Marong', 3515, 'Greater Bendigo City Council'),
        ('Bangholme', 3175, 'Greater Dandenong City Council'),
        ('Keysborough', 3173, 'Greater Dandenong City Council'),
        ('Noble Park', 3174, 'Greater Dandenong City Council'),
        ('Springvale', 3171, 'Greater Dandenong City Council'),
        ('Springvale South', 3172, 'Greater Dandenong City Council'),
        ('Armstrong Creek', 3217, 'Greater Geelong City Council'),
        ('Avalon', 3212, 'Greater Geelong City Council'),
        ('Balliang', 3340, 'Greater Geelong City Council'),
        ('Barwon Heads', 3227, 'Greater Geelong City Council'),
        ('Bell Park', 3215, 'Greater Geelong City Council'),
        ('Bellarine', 3223, 'Greater Geelong City Council'),
        ('Belmont', 3216, 'Greater Geelong City Council'),
        ('Breakwater', 3219, 'Greater Geelong City Council'),
        ('Ceres', 3221, 'Greater Geelong City Council'),
        ('Clifton Springs', 3222, 'Greater Geelong City Council'),
        ('Corio', 3214, 'Greater Geelong City Council'),
        ('Geelong', 3220, 'Greater Geelong City Council'),
        ('Leopold', 3224, 'Greater Geelong City Council'),
        ('Little River', 3211, 'Greater Geelong City Council'),
        ('Ocean Grove', 3226, 'Greater Geelong City Council'),
        ('Point Lonsdale', 3225, 'Greater Geelong City Council'),
        ('Arcadia', 3631, 'Greater Shepparton City Council'),
        ('Ardmona', 3629, 'Greater Shepparton City Council'),
        ('Bunbartha', 3634, 'Greater Shepparton City Council'),
        ('Byrneside', 3617, 'Greater Shepparton City Council'),
        ('Caniambo', 3630, 'Greater Shepparton City Council'),
        ('Congupna', 3633, 'Greater Shepparton City Council'),
        ('Cooma', 3616, 'Greater Shepparton City Council'),
        ('Dhurringile', 3610, 'Greater Shepparton City Council'),
        ('Dookie', 3646, 'Greater Shepparton City Council'),
        ('Dookie College', 3647, 'Greater Shepparton City Council'),
        ('Goulburn Weir', 3608, 'Greater Shepparton City Council'),
        ('Gowangardie', 3669, 'Greater Shepparton City Council'),
        ('Merrigum', 3618, 'Greater Shepparton City Council'),
        ('Toolamba', 3614, 'Greater Shepparton City Council'),
        ('Basalt', 3460, 'Hepburn Shire Council'),
        ('Bullarto', 3461, 'Hepburn Shire Council'),
        ('Drummond North', 3446, 'Hepburn Shire Council'),
        ('Fern Hill', 3458, 'Hepburn Shire Council'),
        ('Guildford', 3451, 'Hepburn Shire Council'),
        ('Taradale', 3447, 'Hepburn Shire Council'),
        ('Antwerp', 3414, 'Hindmarsh Shire Council'),
        ('Broughton', 3418, 'Hindmarsh Shire Council'),
        ('Jeparit', 3423, 'Hindmarsh Shire Council'),
        ('Kaniva', 3419, 'Hindmarsh Shire Council'),
        ('Rainbow', 3424, 'Hindmarsh Shire Council'),
        ('Altona', 3018, 'Hobsons Bay City Council'),
        ('Altona Meadows', 3028, 'Hobsons Bay City Council'),
        ('Altona North', 3025, 'Hobsons Bay City Council'),
        ('Newport', 3015, 'Hobsons Bay City Council'),
        ('Williamstown', 3016, 'Hobsons Bay City Council'),
        ('Arapiles', 3409, 'Horsham Rural City Council'),
        ('Blackheath', 3401, 'Horsham Rural City Council'),
        ('Dadswells Bridge', 3385, 'Horsham Rural City Council'),
        ('Horsham', 3400, 'Horsham Rural City Council'),
        ('Kewell', 3390, 'Horsham Rural City Council'),
        ('Attwood', 3049, 'Hume City Council'),
        ('Broadmeadows', 3047, 'Hume City Council'),
        ('Bulla', 3428, 'Hume City Council'),
        ('Campbellfield', 3061, 'Hume City Council'),
        ('Clarkefield', 3430, 'Hume City Council'),
        ('Coolaroo', 3048, 'Hume City Council'),
        ('Craigieburn', 3064, 'Hume City Council'),
        ('Diggers Rest', 3427, 'Hume City Council'),
        ('Fawkner', 3060, 'Hume City Council'),
        ('Greenvale', 3059, 'Hume City Council'),
        ('Melbourne Airport', 3045, 'Hume City Council'),
        ('Oaklands Junction', 3063, 'Hume City Council'),
        ('Somerton', 3062, 'Hume City Council'),
        ('Sunbury', 3429, 'Hume City Council'),
        ('Barnawartha', 3688, 'Indigo Shire Council'),
        ('Beechworth', 3747, 'Indigo Shire Council'),
        ('Brimin', 3685, 'Indigo Shire Council'),
        ('Bruarong', 3749, 'Indigo Shire Council'),
        ('Charleroi', 3695, 'Indigo Shire Council'),
        ('Chiltern', 3683, 'Indigo Shire Council'),
        ('Lilliput', 3682, 'Indigo Shire Council'),
        ('Wahgunyah', 3687, 'Indigo Shire Council'),
        ('Aspendale', 3195, 'Kingston City Council'),
        ('Bonbeach', 3196, 'Kingston City Council'),
        ('Carrum', 3197, 'Kingston City Council'),
        ('Clarinda', 3169, 'Kingston City Council'),
        ('Heatherton', 3202, 'Kingston City Council'),
        ('Mentone', 3194, 'Kingston City Council'),
        ('Moorabbin', 3189, 'Kingston City Council'),
        ('Oakleigh South', 3167, 'Kingston City Council'),
        ('Bayswater', 3153, 'Knox City Council'),
        ('Boronia', 3155, 'Knox City Council'),
        ('Knoxfield', 3180, 'Knox City Council'),
        ('Rowville', 3178, 'Knox City Council'),
        ('Sassafras', 3787, 'Knox City Council'),
        ('Scoresby', 3179, 'Knox City Council'),
        ('The Basin', 3154, 'Knox City Council'),
        ('Wantirna', 3152, 'Knox City Council'),
        ('Balook', 3971, 'Latrobe City Council'),
        ('Boolarra', 3870, 'Latrobe City Council'),
        ('Callignee', 3844, 'Latrobe City Council'),
        ('Churchill', 3842, 'Latrobe City Council'),
        ('Cowwarr', 3857, 'Latrobe City Council'),
        ('Driffield', 3840, 'Latrobe City Council'),
        ('Glengarry', 3854, 'Latrobe City Council'),
        ('Jumbuk', 3869, 'Latrobe City Council'),
        ('Toongabbie', 3856, 'Latrobe City Council'),
        ('Bears Lagoon', 3517, 'Loddon Shire Council'),
        ('Dingee', 3571, 'Loddon Shire Council'),
        ('Durham Ox', 3576, 'Loddon Shire Council'),
        ('Eastville', 3463, 'Loddon Shire Council'),
        ('Gladfield', 3575, 'Loddon Shire Council'),
        ('Kinypanial', 3520, 'Loddon Shire Council'),
        ('Ashbourne', 3442, 'Macedon Ranges Shire Council'),
        ('Benloch', 3435, 'Macedon Ranges Shire Council'),
        ('Bolinda', 3432, 'Macedon Ranges Shire Council'),
        ('Bullengarook', 3437, 'Macedon Ranges Shire Council'),
        ('Bylands', 3762, 'Macedon Ranges Shire Council'),
        ('Cherokee', 3434, 'Macedon Ranges Shire Council'),
        ('Chintin', 3756, 'Macedon Ranges Shire Council'),
        ('Macedon', 3440, 'Macedon Ranges Shire Council'),
        ('Monegeetta', 3433, 'Macedon Ranges Shire Council'),
        ('Mount Macedon', 3441, 'Macedon Ranges Shire Council'),
        ('New Gisborne', 3438, 'Macedon Ranges Shire Council'),
        ('Riddells Creek', 3431, 'Macedon Ranges Shire Council'),
        ('Tantaraboo', 3764, 'Macedon Ranges Shire Council'),
        ('Toolern Vale', 3337, 'Macedon Ranges Shire Council'),
        ('Bulleen', 3105, 'Manningham City Council'),
        ('Doncaster', 3108, 'Manningham City Council'),
        ('Doncaster East', 3109, 'Manningham City Council'),
        ('Donvale', 3111, 'Manningham City Council'),
        ('Nunawading', 3131, 'Manningham City Council'),
        ('Park Orchards', 3114, 'Manningham City Council'),
        ('Ringwood North', 3134, 'Manningham City Council'),
        ('Templestowe', 3106, 'Manningham City Council'),
        ('Templestowe Lower', 3107, 'Manningham City Council'),
        ('Warrandyte', 3113, 'Manningham City Council'),
        ('Wonga Park', 3115, 'Manningham City Council'),
        ('Ancona', 3715, 'Mansfield Shire Council'),
        ('Barwite', 3722, 'Mansfield Shire Council'),
        ('Bonnie Doon', 3720, 'Mansfield Shire Council'),
        ('Lake Eildon', 3713, 'Mansfield Shire Council'),
        ('Braybrook', 3019, 'Maribyrnong City Council'),
        ('Footscray', 3011, 'Maribyrnong City Council'),
        ('Maribyrnong', 3032, 'Maribyrnong City Council'),
        ('Yarraville', 3013, 'Maribyrnong City Council'),
        ('Croydon', 3136, 'Maroondah City Council'),
        ('Heathmont', 3135, 'Maroondah City Council'),
        ('Kilsyth', 3137, 'Maroondah City Council'),
        ('Vermont', 3133, 'Maroondah City Council'),
        ('Carlton', 3053, 'Melbourne City Council'),
        ('Carlton North', 3054, 'Melbourne City Council'),
        ('Docklands', 3008, 'Melbourne City Council'),
        ('East Melbourne', 3002, 'Melbourne City Council'),
        ('Flemington', 3031, 'Melbourne City Council'),
        ('Melbourne', 3000, 'Melbourne City Council'),
        ('Melbourne', 3004, 'Melbourne City Council'),
        ('North Melbourne', 3051, 'Melbourne City Council'),
        ('Parkville', 3052, 'Melbourne City Council'),
        ('Port Melbourne', 3207, 'Melbourne City Council'),
        ('South Wharf', 3006, 'Melbourne City Council'),
        ('South Yarra', 3141, 'Melbourne City Council'),
        ('West Melbourne', 3003, 'Melbourne City Council'),
        ('Aintree', 3336, 'Melton City Council'),
        ('Bonnie Brook', 3335, 'Melton City Council'),
        ('Brookfield', 3338, 'Melton City Council'),
        ('Fieldstone', 3024, 'Melton City Council'),
        ('Truganina', 3029, 'Melton City Council'),
        ('Brunswick', 3056, 'Merri-bek City Council'),
        ('Brunswick East', 3057, 'Merri-bek City Council'),
        ('Brunswick West', 3055, 'Merri-bek City Council'),
        ('Fitzroy North', 3068, 'Merri-bek City Council'),
        ('Glenroy', 3046, 'Merri-bek City Council'),
        ('Pascoe Vale', 3044, 'Merri-bek City Council'),
        ('Big Desert', 3490, 'Mildura Rural City Council'),
        ('Birdwoodton', 3505, 'Mildura Rural City Council'),
        ('Cardross', 3496, 'Mildura Rural City Council'),
        ('Carina', 3512, 'Mildura Rural City Council'),
        ('Carwarp', 3494, 'Mildura Rural City Council'),
        ('Cowangie', 3506, 'Mildura Rural City Council'),
        ('Hattah', 3501, 'Mildura Rural City Council'),
        ('Irymple', 3498, 'Mildura Rural City Council'),
        ('Linga', 3509, 'Mildura Rural City Council'),
        ('Mildura', 3500, 'Mildura Rural City Council'),
        ('Patchewollock', 3491, 'Mildura Rural City Council'),
        ('Tempy', 3489, 'Mildura Rural City Council'),
        ('Walpeup', 3507, 'Mildura Rural City Council'),
        ('Avenel', 3664, 'Mitchell Shire Council'),
        ('Beveridge', 3753, 'Mitchell Shire Council'),
        ('Broadford', 3658, 'Mitchell Shire Council'),
        ('Glenhope East', 3522, 'Mitchell Shire Council'),
        ('Heathcote Junction', 3758, 'Mitchell Shire Council'),
        ('Highlands', 3660, 'Mitchell Shire Council'),
        ('Mangalore', 3663, 'Mitchell Shire Council'),
        ('Puckapunyal', 3662, 'Mitchell Shire Council'),
        ('Pyalong', 3521, 'Mitchell Shire Council'),
        ('Tallarook', 3659, 'Mitchell Shire Council'),
        ('Tarcombe', 3666, 'Mitchell Shire Council'),
        ('Almonds', 3727, 'Moira Shire Council'),
        ('Barmah', 3639, 'Moira Shire Council'),
        ('Bathumi', 3730, 'Moira Shire Council'),
        ('Bearii', 3641, 'Moira Shire Council'),
        ('Boomahnoomoonah', 3728, 'Moira Shire Council'),
        ('Cobram', 3644, 'Moira Shire Council'),
        ('Drumanure', 3636, 'Moira Shire Council'),
        ('Kaarimba', 3635, 'Moira Shire Council'),
        ('Katamatite', 3649, 'Moira Shire Council'),
        ('Katunga', 3640, 'Moira Shire Council'),
        ('Kotupna', 3638, 'Moira Shire Council'),
        ('Peechelba', 3678, 'Moira Shire Council'),
        ('Waaia', 3637, 'Moira Shire Council'),
        ('Burwood', 3125, 'Monash City Council'),
        ('Chadstone', 3148, 'Monash City Council'),
        ('Clayton', 3168, 'Monash City Council'),
        ('Glen Waverley', 3150, 'Monash City Council'),
        ('Hughesdale', 3166, 'Monash City Council'),
        ('Mount Waverley', 3149, 'Monash City Council'),
        ('Mulgrave', 3170, 'Monash City Council'),
        ('Aberfeldie', 3040, 'Moonee Valley City Council'),
        ('Avondale Heights', 3034, 'Moonee Valley City Council'),
        ('Essendon Fields', 3041, 'Moonee Valley City Council'),
        ('Moonee Ponds', 3039, 'Moonee Valley City Council'),
        ('Bungal', 3334, 'Moorabool Shire Council'),
        ('Dales Creek', 3341, 'Moorabool Shire Council'),
        ('Gordon', 3345, 'Moorabool Shire Council'),
        ('Arthurs Seat', 3936, 'Mornington Peninsula Shire Council'),
        ('Balnarring', 3926, 'Mornington Peninsula Shire Council'),
        ('Bittern', 3918, 'Mornington Peninsula Shire Council'),
        ('Blairgowrie', 3942, 'Mornington Peninsula Shire Council'),
        ('Boneo', 3939, 'Mornington Peninsula Shire Council'),
        ('Capel Sound', 3940, 'Mornington Peninsula Shire Council'),
        ('Crib Point', 3919, 'Mornington Peninsula Shire Council'),
        ('Flinders', 3929, 'Mornington Peninsula Shire Council'),
        ('Hastings', 3915, 'Mornington Peninsula Shire Council'),
        ('Hmas Cerberus', 3920, 'Mornington Peninsula Shire Council'),
        ('Main Ridge', 3928, 'Mornington Peninsula Shire Council'),
        ('McCrae', 3938, 'Mornington Peninsula Shire Council'),
        ('Merricks', 3916, 'Mornington Peninsula Shire Council'),
        ('Moorooduc', 3933, 'Mornington Peninsula Shire Council'),
        ('Mornington', 3931, 'Mornington Peninsula Shire Council'),
        ('Mount Eliza', 3930, 'Mornington Peninsula Shire Council'),
        ('Mount Martha', 3934, 'Mornington Peninsula Shire Council'),
        ('Portsea', 3944, 'Mornington Peninsula Shire Council'),
        ('Red Hill', 3937, 'Mornington Peninsula Shire Council'),
        ('Rye', 3941, 'Mornington Peninsula Shire Council'),
        ('Somers', 3927, 'Mornington Peninsula Shire Council'),
        ('Sorrento', 3943, 'Mornington Peninsula Shire Council'),
        ('Tyabb', 3913, 'Mornington Peninsula Shire Council'),
        ('Castlemaine', 3450, 'Mount Alexander Shire Council'),
        ('Elphinstone', 3448, 'Mount Alexander Shire Council'),
        ('Green Gully', 3462, 'Mount Alexander Shire Council'),
        ('Allansford', 3277, 'Moyne Shire Council'),
        ('Ballangeich', 3279, 'Moyne Shire Council'),
        ('Bushfield', 3281, 'Moyne Shire Council'),
        ('Caramut', 3274, 'Moyne Shire Council'),
        ('Condah Swamp', 3286, 'Moyne Shire Council'),
        ('Crossley', 3283, 'Moyne Shire Council'),
        ('Dennington', 3280, 'Moyne Shire Council'),
        ('Gazette', 3289, 'Moyne Shire Council'),
        ('Hawkesdale', 3287, 'Moyne Shire Council'),
        ('Hexham', 3273, 'Moyne Shire Council'),
        ('Illowa', 3282, 'Moyne Shire Council'),
        ('Mailors Flat', 3275, 'Moyne Shire Council'),
        ('Minjah', 3276, 'Moyne Shire Council'),
        ('Orford', 3284, 'Moyne Shire Council'),
        ('Purnim', 3278, 'Moyne Shire Council'),
        ('Acheron', 3714, 'Murrindindi Shire Council'),
        ('Buxton', 3711, 'Murrindindi Shire Council'),
        ('Castella', 3777, 'Murrindindi Shire Council'),
        ('Flowerdale', 3717, 'Murrindindi Shire Council'),
        ('Gobur', 3719, 'Murrindindi Shire Council'),
        ('Kinglake', 3763, 'Murrindindi Shire Council'),
        ('Kinglake Central', 3757, 'Murrindindi Shire Council'),
        ('Marysville', 3779, 'Murrindindi Shire Council'),
        ('Molesworth', 3718, 'Murrindindi Shire Council'),
        ('Narbethong', 3778, 'Murrindindi Shire Council'),
        ('Rubicon', 3712, 'Murrindindi Shire Council'),
        ('Arthurs Creek', 3099, 'Nillumbik Shire Council'),
        ('Bend Of Islands', 3097, 'Nillumbik Shire Council'),
        ('Christmas Hills', 3775, 'Nillumbik Shire Council'),
        ('Diamond Creek', 3089, 'Nillumbik Shire Council'),
        ('Doreen', 3754, 'Nillumbik Shire Council'),
        ('Panton Hill', 3759, 'Nillumbik Shire Council'),
        ('Plenty', 3090, 'Nillumbik Shire Council'),
        ('Smiths Gully', 3760, 'Nillumbik Shire Council'),
        ('St Andrews', 3761, 'Nillumbik Shire Council'),
        ('Wattle Glen', 3096, 'Nillumbik Shire Council'),
        ('Yan Yean', 3755, 'Nillumbik Shire Council'),
        ('Yarrambat', 3091, 'Nillumbik Shire Council'),
        ('Banyena', 3388, 'Northern Grampians Shire Council'),
        ('Barkly', 3384, 'Northern Grampians Shire Council'),
        ('Bolangum', 3387, 'Northern Grampians Shire Council'),
        ('Stawell', 3380, 'Northern Grampians Shire Council'),
        ('Albert Park', 3206, 'Port Phillip City Council'),
        ('Elwood', 3184, 'Port Phillip City Council'),
        ('South Melbourne', 3205, 'Port Phillip City Council'),
        ('St Kilda', 3182, 'Port Phillip City Council'),
        ('Windsor', 3181, 'Port Phillip City Council'),
        ('Amphitheatre', 3468, 'Pyrenees Shire Council'),
        ('Avoca', 3467, 'Pyrenees Shire Council'),
        ('Agnes', 3962, 'South Gippsland Shire Council'),
        ('Bena', 3946, 'South Gippsland Shire Council'),
        ('Bennison', 3960, 'South Gippsland Shire Council'),
        ('Binginwarri', 3966, 'South Gippsland Shire Council'),
        ('Buffalo', 3958, 'South Gippsland Shire Council'),
        ('Dumbalk', 3956, 'South Gippsland Shire Council'),
        ('Fish Creek', 3959, 'South Gippsland Shire Council'),
        ('Hedley', 3967, 'South Gippsland Shire Council'),
        ('Koonwarra', 3954, 'South Gippsland Shire Council'),
        ('Port Franklin', 3964, 'South Gippsland Shire Council'),
        ('Port Welshpool', 3965, 'South Gippsland Shire Council'),
        ('Stony Creek', 3957, 'South Gippsland Shire Council'),
        ('Balmoral', 3407, 'Southern Grampians Shire Council'),
        ('Bulart', 3314, 'Southern Grampians Shire Council'),
        ('Byaduk North', 3300, 'Southern Grampians Shire Council'),
        ('Dunkeld', 3294, 'Southern Grampians Shire Council'),
        ('Harrow', 3317, 'Southern Grampians Shire Council'),
        ('Armadale', 3143, 'Stonnington City Council'),
        ('Kooyong', 3144, 'Stonnington City Council'),
        ('Toorak', 3142, 'Stonnington City Council'),
        ('Locksley', 3665, 'Strathbogie Shire Council'),
        ('Tabilk', 3607, 'Strathbogie Shire Council'),
        ('Aireys Inlet', 3231, 'Surf Coast Shire Council'),
        ('Anglesea', 3230, 'Surf Coast Shire Council'),
        ('Bellbrae', 3228, 'Surf Coast Shire Council'),
        ('Buckley', 3240, 'Surf Coast Shire Council'),
        ('Lorne', 3232, 'Surf Coast Shire Council'),
        ('Annuello', 3549, 'Swan Hill Rural City Council'),
        ('Beverford', 3590, 'Swan Hill Rural City Council'),
        ('Bolton', 3546, 'Swan Hill Rural City Council'),
        ('Boundary Bend', 3599, 'Swan Hill Rural City Council'),
        ('Bulga', 3586, 'Swan Hill Rural City Council'),
        ('Kenley', 3597, 'Swan Hill Rural City Council'),
        ('Lake Boga', 3584, 'Swan Hill Rural City Council'),
        ('Nyah', 3594, 'Swan Hill Rural City Council'),
        ('Nyah West', 3595, 'Swan Hill Rural City Council'),
        ('Towan', 3596, 'Swan Hill Rural City Council'),
        ('Tresco', 3583, 'Swan Hill Rural City Council'),
        ('Vinifera', 3591, 'Swan Hill Rural City Council'),
        ('Woorinen', 3589, 'Swan Hill Rural City Council'),
        ('Woorinen South', 3588, 'Swan Hill Rural City Council'),
        ('Bullioh', 3700, 'Towong Shire Council'),
        ('Burrowye', 3709, 'Towong Shire Council'),
        ('Cudgewa', 3705, 'Towong Shire Council'),
        ('Koetong', 3704, 'Towong Shire Council'),
        ('Tintaldra', 3708, 'Towong Shire Council'),
        ('Elizabeth Island', 3921, 'Unincorporated Land (victoria)'),
        ('Bowmans Forest', 3735, 'Wangaratta Rural City Council'),
        ('Eldorado', 3746, 'Wangaratta Rural City Council'),
        ('Moyhu', 3732, 'Wangaratta Rural City Council'),
        ('Wangaratta', 3677, 'Wangaratta Rural City Council'),
        ('Whitfield', 3733, 'Wangaratta Rural City Council'),
        ('Airly', 3851, 'Wellington Shire Council'),
        ('Boisdale', 3860, 'Wellington Shire Council'),
        ('Dawson', 3858, 'Wellington Shire Council'),
        ('East Sale', 3852, 'Wellington Shire Council'),
        ('Gormandale', 3873, 'Wellington Shire Council'),
        ('Hiamdale', 3847, 'Wellington Shire Council'),
        ('Maffra West Upper', 3859, 'Wellington Shire Council'),
        ('McLoughlins Beach', 3874, 'Wellington Shire Council'),
        ('Sale', 3850, 'Wellington Shire Council'),
        ('Apsley', 3319, 'West Wimmera Shire Council'),
        ('Charam', 3318, 'West Wimmera Shire Council'),
        ('Goroke', 3412, 'West Wimmera Shire Council'),
        ('Lillimur', 3420, 'West Wimmera Shire Council'),
        ('Minimay', 3413, 'West Wimmera Shire Council'),
        ('Miram', 3415, 'West Wimmera Shire Council'),
        ('Blackburn', 3130, 'Whitehorse City Council'),
        ('Box Hill', 3128, 'Whitehorse City Council'),
        ('Box Hill North', 3129, 'Whitehorse City Council'),
        ('Burwood East', 3151, 'Whitehorse City Council'),
        ('Mitcham', 3132, 'Whitehorse City Council'),
        ('Epping', 3076, 'Whittlesea City Council'),
        ('Lalor', 3075, 'Whittlesea City Council'),
        ('Mill Park', 3082, 'Whittlesea City Council'),
        ('South Morang', 3752, 'Whittlesea City Council'),
        ('Thomastown', 3074, 'Whittlesea City Council'),
        ('Wollert', 3750, 'Whittlesea City Council'),
        ('Woodstock', 3751, 'Whittlesea City Council'),
        ('West Wodonga', 3690, 'Wodonga City Council'),
        ('Point Cook', 3030, 'Wyndham City Council'),
        ('Williams Landing', 3027, 'Wyndham City Council'),
        ('Abbotsford', 3067, 'Yarra City Council'),
        ('Burnley', 3121, 'Yarra City Council'),
        ('Collingwood', 3066, 'Yarra City Council'),
        ('Fitzroy', 3065, 'Yarra City Council'),
        ('Beenak', 3139, 'Yarra Ranges Shire Council'),
        ('Belgrave', 3160, 'Yarra Ranges Shire Council'),
        ('Big Pats Creek', 3799, 'Yarra Ranges Shire Council'),
        ('Chirnside Park', 3116, 'Yarra Ranges Shire Council'),
        ('Coldstream', 3770, 'Yarra Ranges Shire Council'),
        ('Ferny Creek', 3786, 'Yarra Ranges Shire Council'),
        ('Gilderoy', 3797, 'Yarra Ranges Shire Council'),
        ('Kallista', 3791, 'Yarra Ranges Shire Council'),
        ('Kalorama', 3766, 'Yarra Ranges Shire Council'),
        ('Lilydale', 3140, 'Yarra Ranges Shire Council'),
        ('Monbulk', 3793, 'Yarra Ranges Shire Council'),
        ('Montrose', 3765, 'Yarra Ranges Shire Council'),
        ('Mooroolbark', 3138, 'Yarra Ranges Shire Council'),
        ('Mount Dandenong', 3767, 'Yarra Ranges Shire Council'),
        ('Mount Evelyn', 3796, 'Yarra Ranges Shire Council'),
        ('Olinda', 3788, 'Yarra Ranges Shire Council'),
        ('Sherbrooke', 3789, 'Yarra Ranges Shire Council'),
        ('Silvan', 3795, 'Yarra Ranges Shire Council'),
        ('The Patch', 3792, 'Yarra Ranges Shire Council'),
        ('Tremont', 3785, 'Yarra Ranges Shire Council'),
        ('Upwey', 3158, 'Yarra Ranges Shire Council'),
        ('Boolite', 3392, 'Yarriambiack Shire Council'),
        ('Brim', 3391, 'Yarriambiack Shire Council'),
        ('Hopetoun', 3396, 'Yarriambiack Shire Council'),
        ('Lascelles', 3487, 'Yarriambiack Shire Council');