name: Unit test and Docker Build

on:
  push:
    branches:
      - it3

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Login to Docker Hub
        run: echo "dckr_pat_9AyoYPfPO4MhW2cJpUXemz5tss4" | docker login -u greenh47 --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t greenh47/wasteisland:it2 -f iteration2/dockerfile .
          docker push greenh47/wasteisland:it2

      - name: Update EC2 Instance
        id: update-ec2
        uses: appleboy/ssh-action@master
        with:
          host: 34.198.149.11
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Retrieve the current container ID by name
            CURRENT_CONTAINER=$(sudo docker ps --format "{{.Names}}" --filter "name=naughty_burnell")

            # Stop and remove the current container if it exists
            if [ -n "$CURRENT_CONTAINER" ]; then
              sudo docker stop "$CURRENT_CONTAINER"
              sudo docker rm "$CURRENT_CONTAINER"
            fi

            # Pull the updated Docker image
            sudo docker pull greenh47/wasteisland:it2

            # Run a new container with the updated image
            sudo docker run --name naughty_burnell -d -p 8080:80 greenh47/wasteisland:it2
